# Generated by Django 3.1.3 on 2023-07-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230727_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='id',
        ),
        migrations.RemoveField(
            model_name='add',
            name='minutes_required',
        ),
        migrations.RemoveField(
            model_name='add',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='add',
            name='order',
        ),
        migrations.RemoveField(
            model_name='add',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='minutes_required',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='heat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='heat',
            name='minutes_required',
        ),
        migrations.RemoveField(
            model_name='heat',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='heat',
            name='order',
        ),
        migrations.RemoveField(
            model_name='heat',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='wait',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wait',
            name='minutes_required',
        ),
        migrations.RemoveField(
            model_name='wait',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='wait',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wait',
            name='recipe_id',
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_required', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        )
    ]
