# Generated by Django 3.1.3 on 2023-07-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230727_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='procedure_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.procedure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cut',
            name='procedure_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.procedure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heat',
            name='procedure_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.procedure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wait',
            name='procedure_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.procedure'),
            preserve_default=False,
        ),
    ]
